import { defineTopic } from '../define-topic'

export const professionsTopic = defineTopic({
  id: 'professions',
  emoji: '👨‍🔧',
  name: { uz: 'Kasblar', en: 'Professions' },
  words: [
    ['Shifokor', 'Doctor'],
    ['Oʻqituvchi', 'Teacher'],
    ['Politsiyachi', 'Police officer'],
    ['Oʻt oʻchiruvchi', 'Firefighter'],
    ['Uchuvchi', 'Pilot'],
    ['Oshpaz', 'Chef'],
    ['Taksist', 'Taxi driver'],
    ['Dasturchi', 'Programmer'],
    ['Quruvchi', 'Builder'],
    ['Sartarosh', 'Barber'],
    ['Kosmonavt', 'Astronaut'],
    ['Aktyor', 'Actor'],
    ['Qoʻshiqchi', 'Singer'],
    ['Rassom', 'Painter'],
    ['Fotograf', 'Photographer'],
    ['Jurnalist', 'Journalist'],
    ['Advokat', 'Lawyer'],
    ['Sotuvchi', 'Salesperson'],
    ['Dehqon', 'Farmer'],
    ['Elektrik', 'Electrician'],
    ['Santexnik', 'Plumber'],
    ['Stomatolog', 'Dentist'],
    ['Hamshira', 'Nurse'],
    ['Askar', 'Soldier'],
    ['Kassir', 'Cashier'],
    ['Ofitsiant', 'Waiter'],
    ['Kuryer', 'Courier'],
    ['Bloger', 'Blogger'],
    ['Dizayner', 'Designer'],
    ['Mexanik', 'Mechanic'],
    ['Tarjimon', 'Translator'],
    ['Detektiv', 'Detective'],
    ['Qorovul', 'Security guard'],
    ['Sehrgar', 'Magician'],
    ['Hakam', 'Referee'],
  ],
})

export const sportsTopic = defineTopic({
  id: 'sports',
  emoji: '⚽',
  name: { uz: 'Sport turlari', en: 'Sports' },
  words: [
    ['Futbol', 'Football'],
    ['Basketbol', 'Basketball'],
    ['Voleybol', 'Volleyball'],
    ['Tennis', 'Tennis'],
    ['Stol tennisi', 'Table tennis'],
    ['Boks', 'Boxing'],
    ['Kurash', 'Wrestling'],
    ['Dzyudo', 'Judo'],
    ['Karate', 'Karate'],
    ['Taekvondo', 'Taekwondo'],
    ['Suzish', 'Swimming'],
    ['Shaxmat', 'Chess'],
    ['Shashka', 'Checkers'],
    ['Velosport', 'Cycling'],
    ['Gimnastika', 'Gymnastics'],
    ['Ogʻir atletika', 'Weightlifting'],
    ['Xokkey', 'Hockey'],
    ['Golf', 'Golf'],
    ['Beysbol', 'Baseball'],
    ['Regbi', 'Rugby'],
    ['Changʻi sporti', 'Skiing'],
    ['Figurali uchish', 'Figure skating'],
    ['Yugurish', 'Running'],
    ['Kamondan otish', 'Archery'],
    ['Koʻpkari', 'Buzkashi'],
    ['Formula 1', 'Formula 1'],
    ['Badminton', 'Badminton'],
    ['MMA', 'MMA'],
    ['Bilyard', 'Billiards'],
    ['Bouling', 'Bowling'],
    ['Serfing', 'Surfing'],
    ['Qilichbozlik', 'Fencing'],
  ],
})

export const cartoonsTopic = defineTopic({
  id: 'cartoons',
  emoji: '🧸',
  name: { uz: 'Multfilmlar', en: 'Cartoons' },
  words: [
    ['Tom va Jerri', 'Tom and Jerry'],
    ['Masha va Ayiq', 'Masha and the Bear'],
    ['Shrek', 'Shrek'],
    ['Madagaskar', 'Madagascar'],
    ['Kung-fu Panda', 'Kung Fu Panda'],
    ['Muzlik davri', 'Ice Age'],
    ['Qirol Sher', 'The Lion King'],
    ['Aladdin', 'Aladdin'],
    ['Sponj Bob', 'SpongeBob'],
    ['Simpsonlar', 'The Simpsons'],
    ['Smeshariki', 'Kikoriki'],
    ['Fiksiklar', 'The Fixies'],
    ['Luntik', 'Luntik'],
    ['Nu, pogodi!', 'Nu, Pogodi!'],
    ['Minionlar', 'Minions'],
    ['Pokemon', 'Pokémon'],
    ['Naruto', 'Naruto'],
    ['Ben 10', 'Ben 10'],
    ['Mikki Maus', 'Mickey Mouse'],
    ['Vinni-Pux', 'Winnie the Pooh'],
    ['Moana', 'Moana'],
    ['Zootopiya', 'Zootopia'],
    ['Nemoni izlab', 'Finding Nemo'],
    ['Suv parisi', 'The Little Mermaid'],
    ['Pinokkio', 'Pinocchio'],
    ['Rapunsel', 'Tangled'],
    ['Zolushka', 'Cinderella'],
    ['Tarzan', 'Tarzan'],
    ['Mulan', 'Mulan'],
    ['Rio', 'Rio'],
    ['Cheburashka', 'Cheburashka'],
    ['Tachki', 'Cars'],
  ],
})

export const moviesTopic = defineTopic({
  id: 'movies',
  emoji: '🎬',
  name: { uz: 'Kinolar', en: 'Movies' },
  words: [
    ['Titanik', 'Titanic'],
    ['Avatar', 'Avatar'],
    ['Terminator', 'The Terminator'],
    ['Garri Potter', 'Harry Potter'],
    ['Transformerlar', 'Transformers'],
    ['Forsaj', 'Fast & Furious'],
    ['Oʻrgimchak-odam', 'Spider-Man'],
    ['Betmen', 'Batman'],
    ['Temir odam', 'Iron Man'],
    ['Qasoskorlar', 'The Avengers'],
    ['Matritsa', 'The Matrix'],
    ['Yura davri parki', 'Jurassic Park'],
    ['Yulduzli urushlar', 'Star Wars'],
    ['Karib dengizi qaroqchilari', 'Pirates of the Caribbean'],
    ['Jumanji', 'Jumanji'],
    ['Uyda yolgʻiz', 'Home Alone'],
    ['Interstellar', 'Interstellar'],
    ['Joker', 'Joker'],
    ['Gladiator', 'Gladiator'],
    ['King Kong', 'King Kong'],
    ['Godzilla', 'Godzilla'],
    ['Rembo', 'Rambo'],
    ['Rokki', 'Rocky'],
    ['Jon Uik', 'John Wick'],
    ['Sherlok Xolms', 'Sherlock Holmes'],
    ['Jeyms Bond', 'James Bond'],
    ['Tor', 'Thor'],
    ['Venom', 'Venom'],
    ['Dedpul', 'Deadpool'],
    ['Uzuklar hukmdori', 'The Lord of the Rings'],
    ['Dyuna', 'Dune'],
  ],
})

export const footballersTopic = defineTopic({
  id: 'footballers',
  emoji: '🏆',
  name: { uz: 'Futbolchilar', en: 'Footballers' },
  words: [
    ['Messi', 'Messi'],
    ['Ronaldu', 'Ronaldo'],
    ['Neymar', 'Neymar'],
    ['Mbappe', 'Mbappé'],
    ['Xolland', 'Haaland'],
    ['Muhammad Salah', 'Mohamed Salah'],
    ['Modrich', 'Modrić'],
    ['Benzema', 'Benzema'],
    ['Levandovski', 'Lewandowski'],
    ['Garri Keyn', 'Harry Kane'],
    ['Vinisius', 'Vinícius Júnior'],
    ['Bellingem', 'Bellingham'],
    ['De Broyne', 'De Bruyne'],
    ['Griezmann', 'Griezmann'],
    ['Zlatan Ibragimovich', 'Zlatan Ibrahimović'],
    ['Bekxem', 'Beckham'],
    ['Zidan', 'Zidane'],
    ['Ronaldinyo', 'Ronaldinho'],
    ['Maradona', 'Maradona'],
    ['Pele', 'Pelé'],
    ['Buffon', 'Buffon'],
    ['Kasilyas', 'Casillas'],
    ['Serxio Ramos', 'Sergio Ramos'],
    ['Suares', 'Suárez'],
    ['Iniesta', 'Iniesta'],
    ['Lamin Yamal', 'Lamine Yamal'],
    ['Kaka', 'Kaká'],
    ['Anri', 'Thierry Henry'],
    ['Eldor Shomurodov', 'Eldor Shomurodov'],
    ['Abbosbek Fayzullayev', 'Abbosbek Fayzullaev'],
    ['Abduqodir Husanov', 'Abdukodir Khusanov'],
    ['Server Jeparov', 'Server Djeparov'],
  ],
})

export const appsTopic = defineTopic({
  id: 'apps',
  emoji: '🎮',
  name: { uz: 'Ilova va oʻyinlar', en: 'Apps & games' },
  words: [
    ['Telegram', 'Telegram'],
    ['Instagram', 'Instagram'],
    ['YouTube', 'YouTube'],
    ['TikTok', 'TikTok'],
    ['WhatsApp', 'WhatsApp'],
    ['Facebook', 'Facebook'],
    ['Google', 'Google'],
    ['Google Maps', 'Google Maps'],
    ['Yandex Go', 'Yandex Go'],
    ['Netflix', 'Netflix'],
    ['Spotify', 'Spotify'],
    ['Snapchat', 'Snapchat'],
    ['ChatGPT', 'ChatGPT'],
    ['Vikipediya', 'Wikipedia'],
    ['Zoom', 'Zoom'],
    ['Discord', 'Discord'],
    ['Steam', 'Steam'],
    ['PUBG Mobile', 'PUBG Mobile'],
    ['Minecraft', 'Minecraft'],
    ['Clash of Clans', 'Clash of Clans'],
    ['Brawl Stars', 'Brawl Stars'],
    ['Subway Surfers', 'Subway Surfers'],
    ['FIFA', 'FIFA'],
    ['GTA', 'GTA'],
    ['Counter-Strike', 'Counter-Strike'],
    ['Dota 2', 'Dota 2'],
    ['Pinterest', 'Pinterest'],
    ['Payme', 'Payme'],
    ['Click', 'Click'],
    ['Uzum Market', 'Uzum Market'],
    ['Duolingo', 'Duolingo'],
    ['CapCut', 'CapCut'],
    ['Shazam', 'Shazam'],
  ],
})
