import { defineTopic } from '../define-topic'

export const homeTopic = defineTopic({
  id: 'home',
  emoji: '🛋️',
  name: { uz: 'Uy jihozlari', en: 'Household items' },
  words: [
    ['Muzlatkich', 'Fridge'],
    ['Televizor', 'TV'],
    ['Divan', 'Sofa'],
    ['Stol', 'Table'],
    ['Stul', 'Chair'],
    ['Karavot', 'Bed'],
    ['Shkaf', 'Wardrobe'],
    ['Gilam', 'Carpet'],
    ['Koʻzgu', 'Mirror'],
    ['Changyutgich', 'Vacuum cleaner'],
    ['Kir yuvish mashinasi', 'Washing machine'],
    ['Dazmol', 'Iron'],
    ['Choynak', 'Teapot'],
    ['Gaz plita', 'Stove'],
    ['Chiroq', 'Lamp'],
    ['Konditsioner', 'Air conditioner'],
    ['Ventilyator', 'Fan'],
    ['Devor soati', 'Wall clock'],
    ['Parda', 'Curtain'],
    ['Yostiq', 'Pillow'],
    ['Koʻrpa', 'Blanket'],
    ['Kreslo', 'Armchair'],
    ['Eshik', 'Door'],
    ['Deraza', 'Window'],
    ['Vanna', 'Bathtub'],
    ['Blender', 'Blender'],
    ['Fen', 'Hair dryer'],
    ['Pichoq', 'Knife'],
    ['Qoshiq', 'Spoon'],
    ['Pult', 'Remote control'],
    ['Rozetka', 'Socket'],
    ['Supurgi', 'Broom'],
    ['Chelak', 'Bucket'],
    ['Sochiq', 'Towel'],
    ['Kalit', 'Key'],
  ],
})

export const foodTopic = defineTopic({
  id: 'food',
  emoji: '🍕',
  name: { uz: 'Ovqat va ichimliklar', en: 'Food & drinks' },
  words: [
    ['Osh', 'Plov'],
    ['Lagʻmon', 'Lagman'],
    ['Manti', 'Manti'],
    ['Somsa', 'Samsa'],
    ['Shashlik', 'Kebab'],
    ['Chuchvara', 'Dumplings'],
    ['Shoʻrva', 'Soup'],
    ['Non', 'Bread'],
    ['Pitsa', 'Pizza'],
    ['Burger', 'Burger'],
    ['Lavash', 'Shawarma'],
    ['Hot-dog', 'Hot dog'],
    ['Kartoshka fri', 'French fries'],
    ['Sushi', 'Sushi'],
    ['Spagetti', 'Spaghetti'],
    ['Tuxum', 'Egg'],
    ['Pishloq', 'Cheese'],
    ['Asal', 'Honey'],
    ['Shokolad', 'Chocolate'],
    ['Muzqaymoq', 'Ice cream'],
    ['Tort', 'Cake'],
    ['Pechenye', 'Cookies'],
    ['Konfet', 'Candy'],
    ['Choy', 'Tea'],
    ['Kofe', 'Coffee'],
    ['Kola', 'Cola'],
    ['Sharbat', 'Juice'],
    ['Sut', 'Milk'],
    ['Salat', 'Salad'],
    ['Kolbasa', 'Sausage'],
    ['Popkorn', 'Popcorn'],
    ['Guruch', 'Rice'],
  ],
})

export const fruitsTopic = defineTopic({
  id: 'fruits',
  emoji: '🍉',
  name: { uz: 'Meva va sabzavotlar', en: 'Fruits & vegetables' },
  words: [
    ['Olma', 'Apple'],
    ['Nok', 'Pear'],
    ['Uzum', 'Grapes'],
    ['Tarvuz', 'Watermelon'],
    ['Qovun', 'Melon'],
    ['Banan', 'Banana'],
    ['Apelsin', 'Orange'],
    ['Limon', 'Lemon'],
    ['Anor', 'Pomegranate'],
    ['Shaftoli', 'Peach'],
    ['Oʻrik', 'Apricot'],
    ['Gilos', 'Cherry'],
    ['Qulupnay', 'Strawberry'],
    ['Ananas', 'Pineapple'],
    ['Kivi', 'Kiwi'],
    ['Mango', 'Mango'],
    ['Xurmo', 'Persimmon'],
    ['Anjir', 'Fig'],
    ['Kokos', 'Coconut'],
    ['Avokado', 'Avocado'],
    ['Kartoshka', 'Potato'],
    ['Sabzi', 'Carrot'],
    ['Piyoz', 'Onion'],
    ['Sarimsoq', 'Garlic'],
    ['Pomidor', 'Tomato'],
    ['Bodring', 'Cucumber'],
    ['Karam', 'Cabbage'],
    ['Qalampir', 'Pepper'],
    ['Baqlajon', 'Eggplant'],
    ['Qovoq', 'Pumpkin'],
    ['Lavlagi', 'Beetroot'],
    ['Makkajoʻxori', 'Corn'],
  ],
})

export const clothesTopic = defineTopic({
  id: 'clothes',
  emoji: '👕',
  name: { uz: 'Kiyim-kechak', en: 'Clothes' },
  words: [
    ['Koʻylak', 'Shirt'],
    ['Shim', 'Trousers'],
    ['Jinsi', 'Jeans'],
    ['Futbolka', 'T-shirt'],
    ['Kurtka', 'Jacket'],
    ['Palto', 'Coat'],
    ['Kostyum', 'Suit'],
    ['Galstuk', 'Tie'],
    ['Kepka', 'Cap'],
    ['Doʻppi', 'Skullcap'],
    ['Shlyapa', 'Hat'],
    ['Sharf', 'Scarf'],
    ['Qoʻlqop', 'Gloves'],
    ['Paypoq', 'Socks'],
    ['Krossovka', 'Sneakers'],
    ['Tufli', 'Shoes'],
    ['Etik', 'Boots'],
    ['Shippak', 'Slippers'],
    ['Kamar', 'Belt'],
    ['Sviter', 'Sweater'],
    ['Xudi', 'Hoodie'],
    ['Shorti', 'Shorts'],
    ['Pijama', 'Pajamas'],
    ['Chopon', 'Robe'],
    ['Koʻzoynak', 'Glasses'],
    ['Qoʻl soati', 'Wristwatch'],
    ['Uzuk', 'Ring'],
    ['Sumka', 'Bag'],
    ['Ryukzak', 'Backpack'],
    ['Sport kostyumi', 'Tracksuit'],
  ],
})

export const techTopic = defineTopic({
  id: 'tech',
  emoji: '📱',
  name: { uz: 'Texnika va gadjetlar', en: 'Tech & gadgets' },
  words: [
    ['Telefon', 'Smartphone'],
    ['Noutbuk', 'Laptop'],
    ['Kompyuter', 'Computer'],
    ['Planshet', 'Tablet'],
    ['Quloqchin', 'Headphones'],
    ['Klaviatura', 'Keyboard'],
    ['Kompyuter sichqonchasi', 'Computer mouse'],
    ['Monitor', 'Monitor'],
    ['Printer', 'Printer'],
    ['Kamera', 'Camera'],
    ['Dron', 'Drone'],
    ['Robot', 'Robot'],
    ['PlayStation', 'PlayStation'],
    ['Joystik', 'Gamepad'],
    ['Fleshka', 'USB flash drive'],
    ['Zaryadka', 'Charger'],
    ['Powerbank', 'Power bank'],
    ['Mikrofon', 'Microphone'],
    ['Kolonka', 'Speaker'],
    ['Aqlli soat', 'Smartwatch'],
    ['Wi-Fi router', 'Wi-Fi router'],
    ['Kalkulyator', 'Calculator'],
    ['Proyektor', 'Projector'],
    ['VR koʻzoynak', 'VR headset'],
    ['Radio', 'Radio'],
    ['Batareyka', 'Battery'],
    ['Navigator', 'GPS navigator'],
    ['Selfi tayoqcha', 'Selfie stick'],
  ],
})
