import { defineTopic } from '../define-topic'

export const natureTopic = defineTopic({
  id: 'nature',
  emoji: '🏔️',
  name: { uz: 'Tabiat', en: 'Nature' },
  words: [
    ['Togʻ', 'Mountain'],
    ['Daryo', 'River'],
    ['Dengiz', 'Sea'],
    ['Okean', 'Ocean'],
    ['Koʻl', 'Lake'],
    ['Oʻrmon', 'Forest'],
    ['Choʻl', 'Desert'],
    ['Sharshara', 'Waterfall'],
    ['Vulqon', 'Volcano'],
    ['Orol', 'Island'],
    ['Gʻor', 'Cave'],
    ['Kamalak', 'Rainbow'],
    ['Chaqmoq', 'Lightning'],
    ['Momaqaldiroq', 'Thunder'],
    ['Qor', 'Snow'],
    ['Doʻl', 'Hail'],
    ['Shamol', 'Wind'],
    ['Bulut', 'Cloud'],
    ['Quyosh', 'Sun'],
    ['Oy', 'Moon'],
    ['Yulduz', 'Star'],
    ['Tuman', 'Fog'],
    ['Muzlik', 'Glacier'],
    ['Qum', 'Sand'],
    ['Daraxt', 'Tree'],
    ['Gul', 'Flower'],
    ['Barg', 'Leaf'],
    ['Boʻron', 'Storm'],
    ['Zilzila', 'Earthquake'],
    ['Plyaj', 'Beach'],
    ['Botqoq', 'Swamp'],
    ['Tsunami', 'Tsunami'],
  ],
})

export const animalsTopic = defineTopic({
  id: 'animals',
  emoji: '🦁',
  name: { uz: 'Hayvonlar', en: 'Animals' },
  words: [
    ['Sher', 'Lion'],
    ['Yoʻlbars', 'Tiger'],
    ['Fil', 'Elephant'],
    ['Jirafa', 'Giraffe'],
    ['Maymun', 'Monkey'],
    ['Ayiq', 'Bear'],
    ['Boʻri', 'Wolf'],
    ['Tulki', 'Fox'],
    ['Quyon', 'Rabbit'],
    ['Ot', 'Horse'],
    ['Tuya', 'Camel'],
    ['Sigir', 'Cow'],
    ['Qoʻy', 'Sheep'],
    ['Echki', 'Goat'],
    ['It', 'Dog'],
    ['Mushuk', 'Cat'],
    ['Tovuq', 'Chicken'],
    ['Burgut', 'Eagle'],
    ['Pingvin', 'Penguin'],
    ['Delfin', 'Dolphin'],
    ['Akula', 'Shark'],
    ['Kit', 'Whale'],
    ['Timsoh', 'Crocodile'],
    ['Ilon', 'Snake'],
    ['Toshbaqa', 'Turtle'],
    ['Qurbaqa', 'Frog'],
    ['Kenguru', 'Kangaroo'],
    ['Zebra', 'Zebra'],
    ['Panda', 'Panda'],
    ['Tipratikan', 'Hedgehog'],
    ['Sichqon', 'Mouse'],
    ['Toʻtiqush', 'Parrot'],
    ['Boyqush', 'Owl'],
    ['Asalari', 'Bee'],
    ['Kapalak', 'Butterfly'],
    ['Chumoli', 'Ant'],
    ['Begemot', 'Hippo'],
    ['Karkidon', 'Rhino'],
  ],
})

export const placesTopic = defineTopic({
  id: 'places',
  emoji: '🏙️',
  name: { uz: 'Joylar', en: 'Places' },
  words: [
    ['Maktab', 'School'],
    ['Kasalxona', 'Hospital'],
    ['Aeroport', 'Airport'],
    ['Vokzal', 'Train station'],
    ['Bozor', 'Bazaar'],
    ['Supermarket', 'Supermarket'],
    ['Restoran', 'Restaurant'],
    ['Kafe', 'Cafe'],
    ['Kinoteatr', 'Cinema'],
    ['Stadion', 'Stadium'],
    ['Park', 'Park'],
    ['Hayvonot bogʻi', 'Zoo'],
    ['Muzey', 'Museum'],
    ['Kutubxona', 'Library'],
    ['Universitet', 'University'],
    ['Masjid', 'Mosque'],
    ['Bank', 'Bank'],
    ['Pochta', 'Post office'],
    ['Mehmonxona', 'Hotel'],
    ['Sport zal', 'Gym'],
    ['Basseyn', 'Swimming pool'],
    ['Choyxona', 'Teahouse'],
    ['Toʻyxona', 'Wedding hall'],
    ['Sartaroshxona', 'Barbershop'],
    ['Dorixona', 'Pharmacy'],
    ['Politsiya boʻlimi', 'Police station'],
    ['Qamoqxona', 'Prison'],
    ['Sirk', 'Circus'],
    ['Attraksionlar parki', 'Amusement park'],
    ['Avtomoyka', 'Car wash'],
    ['Zapravka', 'Gas station'],
    ['Ofis', 'Office'],
    ['Zavod', 'Factory'],
    ['Qishloq', 'Village'],
    ['Kompyuter klubi', 'Gaming club'],
  ],
})

export const countriesTopic = defineTopic({
  id: 'countries',
  emoji: '🌍',
  name: { uz: 'Davlatlar', en: 'Countries' },
  words: [
    ['Oʻzbekiston', 'Uzbekistan'],
    ['Qozogʻiston', 'Kazakhstan'],
    ['Qirgʻiziston', 'Kyrgyzstan'],
    ['Tojikiston', 'Tajikistan'],
    ['Turkmaniston', 'Turkmenistan'],
    ['Rossiya', 'Russia'],
    ['Turkiya', 'Turkey'],
    ['AQSH', 'USA'],
    ['Xitoy', 'China'],
    ['Yaponiya', 'Japan'],
    ['Janubiy Koreya', 'South Korea'],
    ['Hindiston', 'India'],
    ['Braziliya', 'Brazil'],
    ['Argentina', 'Argentina'],
    ['Germaniya', 'Germany'],
    ['Fransiya', 'France'],
    ['Italiya', 'Italy'],
    ['Ispaniya', 'Spain'],
    ['Angliya', 'England'],
    ['Portugaliya', 'Portugal'],
    ['Misr', 'Egypt'],
    ['Saudiya Arabistoni', 'Saudi Arabia'],
    ['BAA', 'UAE'],
    ['Kanada', 'Canada'],
    ['Avstraliya', 'Australia'],
    ['Meksika', 'Mexico'],
    ['Eron', 'Iran'],
    ['Tailand', 'Thailand'],
    ['Indoneziya', 'Indonesia'],
    ['Shveytsariya', 'Switzerland'],
    ['Gruziya', 'Georgia'],
    ['Ozarbayjon', 'Azerbaijan'],
  ],
})

export const transportTopic = defineTopic({
  id: 'transport',
  emoji: '🚗',
  name: { uz: 'Transport', en: 'Transport' },
  words: [
    ['Avtobus', 'Bus'],
    ['Taksi', 'Taxi'],
    ['Metro', 'Subway'],
    ['Poyezd', 'Train'],
    ['Samolyot', 'Airplane'],
    ['Vertolyot', 'Helicopter'],
    ['Kema', 'Ship'],
    ['Qayiq', 'Boat'],
    ['Velosiped', 'Bicycle'],
    ['Mototsikl', 'Motorcycle'],
    ['Skuter', 'Moped'],
    ['Samokat', 'Kick scooter'],
    ['Tramvay', 'Tram'],
    ['Yuk mashinasi', 'Truck'],
    ['Tez yordam mashinasi', 'Ambulance'],
    ['Oʻt oʻchirish mashinasi', 'Fire truck'],
    ['Politsiya mashinasi', 'Police car'],
    ['Traktor', 'Tractor'],
    ['Raketa', 'Rocket'],
    ['Suv osti kemasi', 'Submarine'],
    ['Havo shari', 'Hot air balloon'],
    ['Limuzin', 'Limousine'],
    ['Ekskavator', 'Excavator'],
    ['Ot arava', 'Horse cart'],
    ['Yaxta', 'Yacht'],
    ['Damas', 'Minivan'],
    ['Kvadrotsikl', 'Quad bike'],
    ['Kosmik kema', 'Spaceship'],
    ['Kanat yoʻli', 'Cable car'],
  ],
})
